### ISSUE TITLE
Consider i686 support

### ISSUE THREAD

**Issue by rapucha** [abraunegg/onedrive#79]
i686 is clearly declared as a not supported architecture, and it is indeed not working. I tried it on my netbook and got a segfault. 

But please note that the hardware I am talking about is not that old, 6 years maybe. Its plenty of that crippled devices still around -- netbooks with weak Atoms. Some lightweight Linux distro is the best they can get these days, so I dare to say i686 support is needed more than one can think.  And it is juts not environmental-friendly to dump them :) 

What is the deal with no i686, is it some tool in use that's missing it or there's no resources for support and testing?

**Comment by rapucha** [comment]
Yes, I am the unlucky one with the cripples Atom. Thanks for that old bug reference, could be useful. 

And thanks for keeping the project alive.

**Comment by rapucha** [comment]
A small update: it my case it fails for Linux Mint Xfce 32-bit, but does work with Arch Linux 2018.07.01 i686(both in VirtualBox).

**Comment by abraunegg** [comment]
Can you provide an installed package comparison between the two systems?

I suspect that it is failing due to some sort of dependancy that is being missed on 32 bit / i686 systems.

**Comment by rapucha** [comment]
Sorry I've updated my prev. comment, please take a look.
I will do what you ask, but I am not sure its the real problem. Here's by core analysis for Linux Mint:
``
Reading symbols from onedrive...done.
[New LWP 1937]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `onedrive'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0068a924 in _d_dso_registry ()
(gdb) backtrace
#0  0x0068a924 in _d_dso_registry ()
#1  0x0067e63b in ?? ()
#2  0x0070113b in __libc_csu_init ()
#3  0xb7bfde13 in __libc_start_main (main=0x668764 <main>, argc=1, argv=0xbfa13dd4, init=0x7010f0 <__libc_csu_init>, 
    fini=0x701150 <__libc_csu_fini>, rtld_fini=0xb7f599b0 <_dl_fini>, stack_end=0xbfa13dcc) at ../csu/libc-start.c:266
#4  0x0061a501 in _start ()
``

**Comment by abraunegg** [comment]
So in summary:

- [ ] Linux Mint Xfce 32-bit (Ubuntu based) - FAILS
- [x] Arch Linux 2018.07.01 i686 (Debian based) - WORKS
- [x] Fedora LXDE i386 28-1.1 (RedHat based) - WORKS

As you already have systems that work / dont work - what needs to be done is to work out what the library differences are between the 2 that work and the one that does not.

As I said above - I suspect that the application is failing due to some sort of dependency that is being missed as a runtime dependency on 32 bit / i686 - but there is no consistency OS wise as to failure:

https://github.com/skilion/onedrive/issues/385

- [ ] `Linux dt-jgreen-01 4.9.0-6-686-pae #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) i686 GNU/Linux`

https://github.com/skilion/onedrive/issues/353

- [ ] `Lubunti 386`

https://github.com/skilion/onedrive/issues/336

- [ ] `Linux bl 4.9.0-6-686-pae #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) i686 GNU/Linux`

https://github.com/abraunegg/onedrive/issues/61

- [ ] `Linux Zephyr3 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 17:59:24 UTC 2018 i686 i686 i686 GNU/Linux`

Can you run `ldd` against the binaries on your 3 systems and provide the output ?? Below is what I have for a x86_64 binary on CentOS 7:

```
        linux-vdso.so.1 =>  (0x00007fff0dfa6000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f55ecd94000)
        libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f55ecadf000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f55ec8db000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f55ec6bf000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f55ec3bd000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f55ec1b5000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f55ebf9f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f55ebbd2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f55ecffd000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f55eb99f000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f55eb775000)
        libssl3.so => /lib64/libssl3.so (0x00007f55eb523000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f55eb2fc000)
        libnss3.so => /lib64/libnss3.so (0x00007f55eafcf000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f55eada0000)
        libplds4.so => /lib64/libplds4.so (0x00007f55eab9c000)
        libplc4.so => /lib64/libplc4.so (0x00007f55ea997000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f55ea759000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f55ea50c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f55ea224000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f55e9ff1000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f55e9ded000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f55e9bde000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f55e9989000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f55e9773000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f55e9501000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f55e90a0000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f55e8e92000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f55e8c8e000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f55e8a75000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f55e8858000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f55e8631000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f55e83fa000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f55e8198000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f55e7f95000)
```

**Comment by rapucha** [comment]
pls check my prev. comment update: it works with ldc on Linux Mint-32

**Comment by rapucha** [comment]
I also believe Arch is not based on Debian, it is of its own kind.

**Comment by rapucha** [comment]
LDD output for DMD-compiled onedrive binary on Linux Mint-32:
'''
	linux-gate.so.1 (0xb7f72000)
	libsqlite3.so.0 => /usr/lib/i386-linux-gnu/libsqlite3.so.0 (0xb7b33000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7b14000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb7b0a000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb7b05000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb7ae7000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb790b000)
	/lib/ld-linux.so.2 (0xb7f74000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7809000)
'''
LDD output for LDC-compiled onedrive binary on Linux Mint-32:
'''
	linux-gate.so.1 (0xb7f5e000)
	libsqlite3.so.0 => /usr/lib/i386-linux-gnu/libsqlite3.so.0 (0xb7d04000)
	libphobos2-ldc-shared.so.78 => /usr/lib/i386-linux-gnu/libphobos2-ldc-shared.so.78 (0xb7896000)
	libdruntime-ldc-shared.so.78 => /usr/lib/i386-linux-gnu/libdruntime-ldc-shared.so.78 (0xb77a5000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb779b000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb777c000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb75a0000)
	/lib/ld-linux.so.2 (0xb7f60000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb749e000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb7499000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb747a000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb745c000)
'''

Other systems will be added to this comment later

**Comment by rapucha** [comment]
Fedora
'''
linux-gate.so.1 (0xb7fb3000)
	libcurl.so.4 => /lib/libcurl.so.4 (0xb7f03000)
	libsqlite3.so.0 => /lib/libsqlite3.so.0 (0xb7ded000)
	libdl.so.2 => /lib/libdl.so.2 (0xb7de8000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb7dc9000)
	libm.so.6 => /lib/libm.so.6 (0xb7cc7000)
	librt.so.1 => /lib/librt.so.1 (0xb7cbd000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb7c9f000)
	libc.so.6 => /lib/libc.so.6 (0xb7afb000)
	/lib/ld-linux.so.2 (0xb7fb5000)
	libnghttp2.so.14 => /lib/libnghttp2.so.14 (0xb7ad1000)
	libidn2.so.0 => /lib/libidn2.so.0 (0xb7ab2000)
	libssh.so.4 => /lib/libssh.so.4 (0xb7a33000)
	libpsl.so.5 => /lib/libpsl.so.5 (0xb7a1f000)
	libssl.so.1.1 => /lib/libssl.so.1.1 (0xb79ae000)
	libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0xb773c000)
	libgssapi_krb5.so.2 => /lib/libgssapi_krb5.so.2 (0xb76e5000)
	libkrb5.so.3 => /lib/libkrb5.so.3 (0xb75f7000)
	libk5crypto.so.3 => /lib/libk5crypto.so.3 (0xb75d9000)
	libcom_err.so.2 => /lib/libcom_err.so.2 (0xb75d4000)
	libldap-2.4.so.2 => /lib/libldap-2.4.so.2 (0xb7577000)
	liblber-2.4.so.2 => /lib/liblber-2.4.so.2 (0xb7566000)
	libz.so.1 => /lib/libz.so.1 (0xb754d000)
	libunistring.so.2 => /lib/libunistring.so.2 (0xb73ca000)
	libkrb5support.so.0 => /lib/libkrb5support.so.0 (0xb73b7000)
	libkeyutils.so.1 => /lib/libkeyutils.so.1 (0xb73b2000)
	libresolv.so.2 => /lib/libresolv.so.2 (0xb739a000)
	libsasl2.so.3 => /lib/libsasl2.so.3 (0xb737a000)
	libssl3.so => /lib/libssl3.so (0xb731d000)
	libsmime3.so => /lib/libsmime3.so (0xb72f0000)
	libnss3.so => /lib/libnss3.so (0xb7192000)
	libnssutil3.so => /lib/libnssutil3.so (0xb7166000)
	libplds4.so => /lib/libplds4.so (0xb7161000)
	libplc4.so => /lib/libplc4.so (0xb715b000)
	libnspr4.so => /lib/libnspr4.so (0xb7117000)
	libselinux.so.1 => /lib/libselinux.so.1 (0xb70e7000)
	libcrypt.so.1 => /lib/libcrypt.so.1 (0xb70bc000)
	libpcre2-8.so.0 => /lib/libpcre2-8.so.0 (0xb7035000)
'''

**Comment by abraunegg** [comment]
Thanks - I am not seeing anything obvious jumping out here at me.

So really the recommendation here based on your testing for 32Bit OS / i686 systems:

* Arch Linux / Fedora - use DMD
* Ubuntu / Debian - use LDC

**Comment by rapucha** [comment]
Can confirm Linux Mint Xfce 32-bit LDC workaround is functional on a real hardware.

**Comment by abraunegg** [comment]
Thanks - greatly appreciated for digging into this.

**Comment by abraunegg** [comment]
Can you help validate the contents of this updated readme:

https://github.com/abraunegg/onedrive/blob/update-readme-for-i686-and-ARM-support/README.md

**Comment by rapucha** [comment]
looks fine. I would just add more details on potential problems, like DMD in i686(workaround exists, use LDC) and ARMv6(no workaround found, take a better board). I am going to test 2 more boards (RPi model B+ and RPi3) and update you.

**Comment by abraunegg** [comment]
Thanks for the confirmations. 

What I will also do is open a case against DMD itself as the builds for i386 / i686 on Ubuntu / Debian "should" work but it is definitely a compiler issue here.

**Comment by abraunegg** [comment]
Opened this issue against DMD compiler - https://issues.dlang.org/show_bug.cgi?id=19116

**Comment by abraunegg** [comment]
Resolved by https://github.com/abraunegg/onedrive/commit/e07ee71ad230fe0fb314a8149f145323455877c4

**Comment by abraunegg** [comment]
@rapucha 

I am trying to replicate your feedback:

> A workaround for Linux Mint Xfce 32-bit (hopefully for all Debian family): Use ldc. App compiled with ldc works.

Under Debian `Linux debian 4.9.0-7-686-pae #1 SMP Debian 4.9.110-1 (2018-07-05) i686 GNU/Linux` ldc will not work (ELF issue), and the DMD binary still builds a broken client when run.

As there is no native i686 client for LDC, how did you get it to compile?

**Comment by abraunegg** [comment]
This is the fix for Debian i386 / i686 systems:
```
mkdir ldc && cd ldc
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/ldc_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/libphobos2-ldc-shared-dev_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/ldc/libphobos2-ldc-shared78_1.8.0-3_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/l/llvm-toolchain-5.0/libllvm5.0_5.0.1-2~bpo9+1_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/n/ncurses/libtinfo6_6.1+20180714-1_i386.deb
sudo dpkg -i ./*.deb
```
then to build:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make make DC=/usr/bin/ldmd2
sudo make install
```
